run:
	cmake -B build && cmake --build build && ./build/Debug/Kyros
	cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build && ./build/Debug/Kyros

test:
	cmake -B tests && cmake --build tests && ./tests/Debug/ClientTests